[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20

startup_mode = "Windowed"

dimensions.columns = 110
dimensions.lines = 30

decorations = "Buttonless"
opacity = 0.8
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 18.0

