
require('core.plugins')
require('core.mappings')
require('core.configs')
require('core.colors')

require('plugins.treesitter')
require('plugins.neotree')
require('plugins.lsp')
require('plugins.lualine')
require('plugins.bufferline')
require('plugins.toggleterm')
require('plugins.telescope')
require('plugins.cmp')
require('plugins.mason')
require('plugins.mini')
require('plugins.gitsign')
